image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Docker
  command: sudo docker-up
- name: Install
  command: pip install -e .
- name: Default
  command: echo "Welcome to Ersilia developer terminal"
