image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Docker
  command: sudo docker-up
- name: Install
  command: pip install ersilia # To-do install in developer mode
- name: Default
  command: cd .
