# Write secrets

name: Write Secrets

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Write json file
      - name: Write secrets to json file
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_CONSOLE_LOGIN: ${{ secrets.AWS_CONSOLE_LOGIN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          OSF_PASSWORD: ${{ secrets.OSF_PASSWORD }}
          OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
        run: python .github/scripts/write_secrets.py
      # Push to private ersilia-secrets repository
      - name: Push to ersilia-secrets repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: secrets.json
          destination_repo: 'ersilia-os/ersilia-secrets'
          destination_folder: '.'
          destination_branch: 'main'
          user_email: 'miquelduranfrigola@gmail.com'
          user_name: 'miquelduranfrigola'
